services:
  backend:
    build: ./backend
    container_name: back_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db-redis
    environment:
      - REDIS_HOST=db-redis
      - REDIS_PORT=6379

  db-redis:
    image: redis:alpine
    container_name: db_redis
    ports:
      - "6378:6379"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    stdin_open: true
    tty: true
